
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export const getStaticProps = async () => {
  const response = await fetch('https://pokeapi.co/api/v2/pokemon?limit=151');
  const data = await response.json();
  return {
    props: { pokemones: data.results }
  }
}

export default function RootLayout({ children }) {
  let data = getStaticProps()
  return (
    <html lang="en">
      <body >{children}</body>
    </html>
  )
}
